### ISSUE TITLE
Type errors after upgrading to v4.0.3

### ISSUE THREAD

**Issue by simonihmig** [emberjs/ember-test-helpers#1502]
The latest version, more specifically this [PR](https://github.com/emberjs/ember-test-helpers/pull/1486), seems to cause type errors when upgrading, at least when using a not so recent Ember version and non-native types. 

The published `declarations/settled.d.ts` file has this as its first line:

```ts
export declare const checkWaiters: typeof import("ember-testing/lib/test/waiters").checkWaiters;
```

This probably works if you have latest native types (idk, I assume), but it fails for us with:

```
      [types] ../../../../node_modules/@ember/test-helpers/declarations/settled.d.ts:1:50 - error TS2307: Cannot find module 'ember-testing/lib/test/waiters' or its corresponding type declarations.
      [types] 
      [types] 1 export declare const checkWaiters: typeof import("ember-testing/lib/test/waiters").checkWaiters;
```

I don't think there is a need to expose that checkWaiters type to the outside, it is only used internally, isn't it?

cc @NullVoxPopuli

**Comment by NullVoxPopuli** [comment]
You make a good point -- here is a PR that removes the export: https://github.com/emberjs/ember-test-helpers/pull/1503
