### ISSUE TITLE
Cannot find type definition file for 'ember__test-helpers' after upgrading to v2.9.3

### ISSUE THREAD

**Issue by flashios09** [emberjs/ember-test-helpers#1322]
Hi,
I'm having an error on tsconfig.json after upgrading to v2.9.3

![image](https://user-images.githubusercontent.com/1313482/213261234-a83c082b-435b-4b38-9c1c-15046096ebca.png)

It was working fine with v2.8.1 before the changes on `@types/ember__test-helpers` !

Those are the current version of related dependencies:
- typescript 4.9.4
- qunit 2.19.3
- ember-qunit 6.1.1
- @types/qunit 2.19.4
- @types/ember-qunit 5.0.2

**Comment by oliverlj** [comment]
@types/ember__test-helpers is not needed after version 2.9.0

**Comment by flashios09** [comment]
> @types/ember__test-helpers is not needed after version 2.9.0

@oliverlj For a reason that I ignore, typescript wasn't able to find the **types** after moving it from
 `@types/ember__test-helpers` to `@ember/test-helpers` !

**Comment by NullVoxPopuli** [comment]
Looks like this is resolved -- if not, lemme know!
